In [2]:
import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

Q1. data type
number of dimensions
shape
total number of elements

In [3]:
print(emp_ages)

print(f"Employee ages arrays data type: {emp_ages.dtype}")
print(f"Employee ages arrays number of dimensions: {emp_ages.ndim}")
print(f"Employee ages arrays shape: {emp_ages.shape}")
print(f"Employee ages arrays total number of elements: {emp_ages.size}")

print("\n")
print(emp_income)
print(f"Employee income arrays data type: {emp_income.dtype}")
print(f"Employee income arrays number of dimensions: {emp_income.ndim}")
print(f"Employee income arrays shape: {emp_income.shape}")
print(f"Employee income arrays total number of elements: {emp_income.size}")

[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
Employee ages arrays data type: int32
Employee ages arrays number of dimensions: 1
Employee ages arrays shape: (50,)
Employee ages arrays total number of elements: 50


[51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]
Employee income arrays data type: int32
Employee income arrays number of dimensions: 1
Employee income arrays shape: (50,)
Employee income arrays total number of elements: 50

Q2. Find the maximum and minimum salary
Calculate the average salary
Calculate the average age
 Print all results.

In [4]:
emp_income

array([51725, 38495, 35452, 82295, 72187, 58915, 76159, 92864, 76155,
       90494, 68641, 48079, 56879, 83682, 94722, 91041, 48899, 68744,
       63187, 74146, 75641, 47678, 76760, 78354, 60584, 79898, 59682,
       71888, 51086, 73700, 82550, 71447, 76100, 72269, 73314, 87428,
       94427, 84188, 52013, 63326, 44396, 59500, 55523, 58602, 90794,
       41061, 82331, 73048, 59727, 50398], dtype=int32)

In [5]:
maximum_salary = np.max(emp_income)
print(f"Maximum Salary is: {maximum_salary}")

minimum_salary = np.min(emp_income)
print(f"Minimum Salary is: {minimum_salary}")

average_salary = np.mean(emp_income)
print(f"Average Salary is: {average_salary}")

average_age = np.mean(emp_ages)
print(f"Average Age is: {average_age}")

Maximum Salary is: 94722
Minimum Salary is: 35452
Average Salary is: 68409.48
Average Age is: 35.44

Q3. From the emp_ages array:
Extract employees who:
are aged between 25 and 40,
 AND
Emp_salary : have salary greater than 50,000
Then : 
Print the filtered values
Count how many employees satisfy this condition

In [6]:
mask = ((emp_ages >= 25) & (emp_ages <= 40) & (emp_income > 50000))
print("Ages:", emp_ages[mask])
print("Salaries:", emp_income[mask])
print("Count of employees:", np.count_nonzero(mask))

Ages: [37 37 35 38 31 29 38 27 32 26 37 26 30 30 27 25 31]
Salaries: [72187 58915 92864 90494 68641 56879 83682 94722 74146 78354 79898 59682
 73700 84188 52013 63326 59727]
Count of employees: 17

In [7]:
print(len(emp_income))
print(len(emp_ages))

50
50

Q4. Add 4 years if age is less than the average age
Add 2 years if age is greater than or equal to the average age
original array
updated array
average age used for condition

In [8]:
average_age

np.float64(35.44)

In [9]:
updated_array = np.where(emp_ages >= average_age, emp_ages+2, emp_ages+4)
updated_array

print(f"Original array: {emp_ages}")
print(f"Updated array: {updated_array}")
print(f"Average age: {average_age}")

Original array: [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
Updated array: [56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]
Average age: 35.44

q5

In [10]:
emp_roles

array(['HR Manager', 'Accountant', 'Operations Manager',
       'Digital Marketer', 'Backend Developer', 'HR Manager',
       'Backend Developer', 'Sales Executive', 'Sales Executive',
       'HR Executive', 'Backend Developer', 'Marketing Executive',
       'Sales Executive', 'Operations Manager', 'Digital Marketer',
       'Financial Analyst', 'Sales Executive', 'Operations Manager',
       'Software Developer', 'Backend Developer', 'Sales Executive',
       'Sales Executive', 'Accountant', 'Software Developer',
       'HR Executive', 'Operations Manager', 'Digital Marketer',
       'HR Executive', 'Software Developer', 'Accountant',
       'Sales Executive', 'Marketing Executive', 'Digital Marketer',
       'Backend Developer', 'Software Developer', 'Software Developer',
       'Sales Executive', 'Accountant', 'HR Manager', 'Sales Executive',
       'Marketing Executive', 'Digital Marketer', 'HR Executive',
       'Accountant', 'HR Executive', 'HR Manager', 'Software Developer',
       'Software Developer', 'Digital Marketer', 'Marketing Executive'],
      dtype='<U19')

In [11]:
tech_roles = ((emp_roles == 'Backend Developer') | (emp_roles == 'Digital Marketer') | (emp_roles == 'Software Developer'))

salary = emp_income[tech_roles]

increased_salary = emp_income[tech_roles] * 1.08

sum_of_salary = np.sum(salary)

sum_of_increased_salary = np.sum(increased_salary)

salary_difference = sum_of_increased_salary - sum_of_salary

print(f"Sum of total salary: {sum_of_salary}")
print(f"Sum of new total increased salary: {sum_of_increased_salary}")
print(f"Old and new totals difference: {salary_difference}")

Sum of total salary: 1304176
Sum of new total increased salary: 1408510.08
Old and new totals difference: 104334.08000000007

Q6

In [12]:
df = pd.read_csv('staff_data.csv')

print(df.head(3))
print(df.info())
print(df.describe())

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     str
dtypes: int64(3), str(1)
memory usage: 1.7 KB
None
          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

### Q7

In [13]:
df.head()

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager
3     104       43       82295    Digital Marketer
4     105       37       72187   Backend Developer

In [15]:
df.loc[(df['emp_age'] >= 25) & (df['emp_age'] <= 40)].sort_values('emp_id').tail(3)

    emp_id  emp_age  emp_salary                 role
39     140       25       63326      Sales Executive
40     141       39       44396  Marketing Executive
48     149       31       59727     Digital Marketer

##### Q8 Filter the DataFrame to show only employees working in the "HR" role.
Print the filtered data
Show the total number of HR employees

In [23]:
df

    emp_id  emp_age  emp_salary                 role
0      101       54       51725           HR Manager
1      102       23       38495           Accountant
2      103       20       35452   Operations Manager
3      104       43       82295     Digital Marketer
4      105       37       72187    Backend Developer
5      106       37       58915           HR Manager
6      107       21       76159    Backend Developer
7      108       35       92864      Sales Executive
8      109       24       76155      Sales Executive
9      110       38       90494         HR Executive
10     111       31       68641    Backend Developer
11     112       35       48079  Marketing Executive
12     113       29       56879      Sales Executive
13     114       38       83682   Operations Manager
14     115       27       94722     Digital Marketer
15     116       45       91041    Financial Analyst
16     117       51       48899      Sales Executive
17     118       48       68744   Operations Manager
18     119       20       63187   Software Developer
19     120       32       74146    Backend Developer
20     121       51       75641      Sales Executive
21     122       53       47678      Sales Executive
22     123       21       76760           Accountant
23     124       26       78354   Software Developer
24     125       53       60584         HR Executive
25     126       37       79898   Operations Manager
26     127       26       59682     Digital Marketer
27     128       21       71888         HR Executive
28     129       45       51086   Software Developer
29     130       30       73700           Accountant
30     131       20       82550      Sales Executive
31     132       47       71447  Marketing Executive
32     133       53       76100     Digital Marketer
33     134       53       72269    Backend Developer
34     135       23       73314   Software Developer
35     136       24       87428   Software Developer
36     137       21       94427      Sales Executive
37     138       30       84188           Accountant
38     139       27       52013           HR Manager
39     140       25       63326      Sales Executive
40     141       39       44396  Marketing Executive
41     142       20       59500     Digital Marketer
42     143       47       55523         HR Executive
43     144       41       58602           Accountant
44     145       22       90794         HR Executive
45     146       52       41061           HR Manager
46     147       42       82331   Software Developer
47     148       54       73048   Software Developer
48     149       31       59727     Digital Marketer
49     150       50       50398  Marketing Executive

In [30]:
hr_df = df.loc[df['role'].str.contains('HR')]
print(hr_df)

print(f"Total number of HR's: {len(hr_df)}")

    emp_id  emp_age  emp_salary          role
0      101       54       51725    HR Manager
5      106       37       58915    HR Manager
9      110       38       90494  HR Executive
24     125       53       60584  HR Executive
27     128       21       71888  HR Executive
38     139       27       52013    HR Manager
42     143       47       55523  HR Executive
44     145       22       90794  HR Executive
45     146       52       41061    HR Manager
Total number of HR's: 9

Sort the DataFrame by:
emp_age (ascending)
and then by emp_salary (descending)
Display the top 5 employees after sorting, including:
emp_id
role
emp_salary

In [46]:
df.sort_values(['emp_age', 'emp_salary'], ascending=[1,0]).iloc[:5, [0,3,2]]

    emp_id                role  emp_salary
30     131     Sales Executive       82550
18     119  Software Developer       63187
41     142    Digital Marketer       59500
2      103  Operations Manager       35452
36     137     Sales Executive       94427

Using .loc:
Increase salary by 12% for "Software Developer" and "Backend Developer"
Increase salary by 5% for all other roles
Then:
Print the dataframe that includes role , previous_salary , new_salary , increase_of_salary

In [ ]:
df['new_salary'] = df.loc[df['role'].str.contains("Developer")].iloc[:,2:3] * 1.12
df

    emp_id  emp_age  emp_salary                 role  new_salary
0      101       54       51725           HR Manager         NaN
1      102       23       38495           Accountant         NaN
2      103       20       35452   Operations Manager         NaN
3      104       43       82295     Digital Marketer         NaN
4      105       37       72187    Backend Developer    80849.44
5      106       37       58915           HR Manager         NaN
6      107       21       76159    Backend Developer    85298.08
7      108       35       92864      Sales Executive         NaN
8      109       24       76155      Sales Executive         NaN
9      110       38       90494         HR Executive         NaN
10     111       31       68641    Backend Developer    76877.92
11     112       35       48079  Marketing Executive         NaN
12     113       29       56879      Sales Executive         NaN
13     114       38       83682   Operations Manager         NaN
14     115       27       94722     Digital Marketer         NaN
15     116       45       91041    Financial Analyst         NaN
16     117       51       48899      Sales Executive         NaN
17     118       48       68744   Operations Manager         NaN
18     119       20       63187   Software Developer    70769.44
19     120       32       74146    Backend Developer    83043.52
20     121       51       75641      Sales Executive         NaN
21     122       53       47678      Sales Executive         NaN
22     123       21       76760           Accountant         NaN
23     124       26       78354   Software Developer    87756.48
24     125       53       60584         HR Executive         NaN
25     126       37       79898   Operations Manager         NaN
26     127       26       59682     Digital Marketer         NaN
27     128       21       71888         HR Executive         NaN
28     129       45       51086   Software Developer    57216.32
29     130       30       73700           Accountant         NaN
30     131       20       82550      Sales Executive         NaN
31     132       47       71447  Marketing Executive         NaN
32     133       53       76100     Digital Marketer         NaN
33     134       53       72269    Backend Developer    80941.28
34     135       23       73314   Software Developer    82111.68
35     136       24       87428   Software Developer    97919.36
36     137       21       94427      Sales Executive         NaN
37     138       30       84188           Accountant         NaN
38     139       27       52013           HR Manager         NaN
39     140       25       63326      Sales Executive         NaN
40     141       39       44396  Marketing Executive         NaN
41     142       20       59500     Digital Marketer         NaN
42     143       47       55523         HR Executive         NaN
43     144       41       58602           Accountant         NaN
44     145       22       90794         HR Executive         NaN
45     146       52       41061           HR Manager         NaN
46     147       42       82331   Software Developer    92210.72
47     148       54       73048   Software Developer    81813.76
48     149       31       59727     Digital Marketer         NaN
49     150       50       50398  Marketing Executive         NaN

In [ ]:
df['new_salary'] = df.loc[~df['role'].str.contains("Developer")].iloc[:,2:3] * 1.05

    emp_id  emp_age  emp_salary                 role  new_salary
0      101       54       51725           HR Manager    54311.25
1      102       23       38495           Accountant    40419.75
2      103       20       35452   Operations Manager    37224.60
3      104       43       82295     Digital Marketer    86409.75
4      105       37       72187    Backend Developer         NaN
5      106       37       58915           HR Manager    61860.75
6      107       21       76159    Backend Developer         NaN
7      108       35       92864      Sales Executive    97507.20
8      109       24       76155      Sales Executive    79962.75
9      110       38       90494         HR Executive    95018.70
10     111       31       68641    Backend Developer         NaN
11     112       35       48079  Marketing Executive    50482.95
12     113       29       56879      Sales Executive    59722.95
13     114       38       83682   Operations Manager    87866.10
14     115       27       94722     Digital Marketer    99458.10
15     116       45       91041    Financial Analyst    95593.05
16     117       51       48899      Sales Executive    51343.95
17     118       48       68744   Operations Manager    72181.20
18     119       20       63187   Software Developer         NaN
19     120       32       74146    Backend Developer         NaN
20     121       51       75641      Sales Executive    79423.05
21     122       53       47678      Sales Executive    50061.90
22     123       21       76760           Accountant    80598.00
23     124       26       78354   Software Developer         NaN
24     125       53       60584         HR Executive    63613.20
25     126       37       79898   Operations Manager    83892.90
26     127       26       59682     Digital Marketer    62666.10
27     128       21       71888         HR Executive    75482.40
28     129       45       51086   Software Developer         NaN
29     130       30       73700           Accountant    77385.00
30     131       20       82550      Sales Executive    86677.50
31     132       47       71447  Marketing Executive    75019.35
32     133       53       76100     Digital Marketer    79905.00
33     134       53       72269    Backend Developer         NaN
34     135       23       73314   Software Developer         NaN
35     136       24       87428   Software Developer         NaN
36     137       21       94427      Sales Executive    99148.35
37     138       30       84188           Accountant    88397.40
38     139       27       52013           HR Manager    54613.65
39     140       25       63326      Sales Executive    66492.30
40     141       39       44396  Marketing Executive    46615.80
41     142       20       59500     Digital Marketer    62475.00
42     143       47       55523         HR Executive    58299.15
43     144       41       58602           Accountant    61532.10
44     145       22       90794         HR Executive    95333.70
45     146       52       41061           HR Manager    43114.05
46     147       42       82331   Software Developer         NaN
47     148       54       73048   Software Developer         NaN
48     149       31       59727     Digital Marketer    62713.35
49     150       50       50398  Marketing Executive    52917.90

In [69]:
mask = df['role'].isin(['Software Developer', 'Backend Developer'])

df['previous_salary'] = df['emp_salary']

df.loc[mask, 'new_salary'] = df.loc[mask, 'emp_salary'] * 1.12
df.loc[~mask, 'new_salary'] = df.loc[~mask, 'emp_salary'] * 1.05

df['increase_of_salary'] = df['new_salary'] - df['previous_salary']

df[['role', 'previous_salary', 'new_salary', 'increase_of_salary']]

                   role  previous_salary  new_salary  increase_of_salary
0            HR Manager            51725    54311.25             2586.25
1            Accountant            38495    40419.75             1924.75
2    Operations Manager            35452    37224.60             1772.60
3      Digital Marketer            82295    86409.75             4114.75
4     Backend Developer            72187    80849.44             8662.44
5            HR Manager            58915    61860.75             2945.75
6     Backend Developer            76159    85298.08             9139.08
7       Sales Executive            92864    97507.20             4643.20
8       Sales Executive            76155    79962.75             3807.75
9          HR Executive            90494    95018.70             4524.70
10    Backend Developer            68641    76877.92             8236.92
11  Marketing Executive            48079    50482.95             2403.95
12      Sales Executive            56879    59722.95             2843.95
13   Operations Manager            83682    87866.10             4184.10
14     Digital Marketer            94722    99458.10             4736.10
15    Financial Analyst            91041    95593.05             4552.05
16      Sales Executive            48899    51343.95             2444.95
17   Operations Manager            68744    72181.20             3437.20
18   Software Developer            63187    70769.44             7582.44
19    Backend Developer            74146    83043.52             8897.52
20      Sales Executive            75641    79423.05             3782.05
21      Sales Executive            47678    50061.90             2383.90
22           Accountant            76760    80598.00             3838.00
23   Software Developer            78354    87756.48             9402.48
24         HR Executive            60584    63613.20             3029.20
25   Operations Manager            79898    83892.90             3994.90
26     Digital Marketer            59682    62666.10             2984.10
27         HR Executive            71888    75482.40             3594.40
28   Software Developer            51086    57216.32             6130.32
29           Accountant            73700    77385.00             3685.00
30      Sales Executive            82550    86677.50             4127.50
31  Marketing Executive            71447    75019.35             3572.35
32     Digital Marketer            76100    79905.00             3805.00
33    Backend Developer            72269    80941.28             8672.28
34   Software Developer            73314    82111.68             8797.68
35   Software Developer            87428    97919.36            10491.36
36      Sales Executive            94427    99148.35             4721.35
37           Accountant            84188    88397.40             4209.40
38           HR Manager            52013    54613.65             2600.65
39      Sales Executive            63326    66492.30             3166.30
40  Marketing Executive            44396    46615.80             2219.80
41     Digital Marketer            59500    62475.00             2975.00
42         HR Executive            55523    58299.15             2776.15
43           Accountant            58602    61532.10             2930.10
44         HR Executive            90794    95333.70             4539.70
45           HR Manager            41061    43114.05             2053.05
46   Software Developer            82331    92210.72             9879.72
47   Software Developer            73048    81813.76             8765.76
48     Digital Marketer            59727    62713.35             2986.35
49  Marketing Executive            50398    52917.90             2519.90